language: node_js

node_js:
  - "0.11"
  - "0.10"

cache:
  directories:
    - node_modules

branches:
  except:
    - gh-pages

before_script:
  - npm install -g grunt-cli

script:
  - grunt jshint test